### ISSUE TITLE
Failed to install ghc8.0 and ghc8.2 on ubuntu-24.04

### ISSUE THREAD

**Issue by July541** [haskell-actions/setup#101]
Github runners currently switched `ubuntu-latest` from `ubuntu-22.04` to `ubuntu-24.04`, which made ghc8.0 and ghc 8.2 install failed. See debug log [here](https://github.com/July541/haskell-setup/actions/runs/12374689377/job/34537814222?pr=1).

That is because `libncurses5` and `libtinfo5` install failed: https://github.com/haskell-actions/setup/blob/dd344bc1cec854a369df8814ce17ef337d6e6170/src/installer.ts#L278-L286

And then `/usr/local/.ghcup/tmp/ghcup-3ba2aace02c1cc3e/usr/local/.ghcup/ghc/8.2.2/lib/ghc-8.2.2/bin/ghc-pkg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory`.

Related issue: https://github.com/haskell/ghcup-hs/issues/947

**Comment by andreasabel** [comment]
Thanks for the heads up!

So I suppose GHC 8.0 and 8.2 will become unsupported.  (They are already not supported by latest Stack anymore.)
Or do you know an easy fix?

**Comment by July541** [comment]
Adding an extra source can fix it, see my test [here](https://github.com/July541/haskell-setup/pull/1/files#diff-3d2b59189eeedc2d428ddd632e97658fe310f587f7cb63b01f9b98ffc11c0197).

But I'm not sure if it is worth to do.

**Comment by andreasabel** [comment]
Well if it is just one line...  
I am happy to get this as a PR (after some cleanup and maybe a comment added to the `deb` command that this is necessary for ubuntu 24.04.
