### ISSUE TITLE
Add cabal-install 3.10.2.1

### ISSUE THREAD

**Issue by ulysses4ever** [haskell-actions/setup#56]
The current latest, provided by this action, is 3.10.2.0, which has an unfortunate bug in its `--version` interface.

**Comment by andreasabel** [comment]
I have been told by @Kleidukos that this is not a version that is relevant for binary release.  
- #53
- https://github.com/haskell/ghcup-metadata/issues/147

It is actually working well in vanilla cases:
```
$ cabal-3.10.2.0 --version
cabal-install version 3.10.2.0
compiled using version 3.10.2.1 of the Cabal library 
```

But I am happy to be told otherwise...

**Comment by Kleidukos** [comment]
yes because the 3.10.2.0 distributed by ghcup doesn't suffer from this

**Comment by ulysses4ever** [comment]
SGTM, sorry for the noise.
