### ISSUE TITLE
Fix "Model cabal workflow with caching" example 

### ISSUE THREAD

**Issue by sestrella** [haskell-actions/setup#58]
There is a small typo in the "Model cabal workflow with caching" example":

https://github.com/haskell-actions/setup#model-cabal-workflow-with-caching

```diff
+ ghc-version: ['9.8', '9.6', '9.4', '9.2', '9.0']
- ghc-version: ['9.8, '9.6', '9.4', '9.2', '9.0']
```

**Comment by andreasabel** [comment]
Closed by #57.
