### ISSUE TITLE
Connection Timeout with Stack Commands

### ISSUE THREAD

**Issue by asarkar** [haskell-actions/setup#93]
I've been using [haskell/actions/setup@v2](https://github.com/haskell/actions/tree/main/setup), which has now been deprecated in favor of `haskell-actions/setup`. However, while using that action, I started encountering connection timeouts whenever I ran any `stack` command. This issue seems to have been reported by several others on platforms like the [Haskell forum](https://discourse.haskell.org/t/stack-build-and-pretty-much-any-stack-command-runs-into-a-connection-timeout/8068), [StackOverflow](https://stackoverflow.com/q/57962794/839733), and [Stack GitHub](https://github.com/commercialhaskell/stack/issues/5063), but no definitive solution has been found so far.

Here's a [run](https://github.com/asarkar/exercism-haskell/actions/runs/10514723223/job/29133213193) that failed due to this issue.

Some of the suggestions I found include disabling IPV6, and/or switching to Google DNS servers.

Switching to `haskell-actions/setup@v2` resolved the issue on GitHub, and the timeout problem disappeared. However, I couldn't find any documentation in this repo or issues that indicate what exactly changed to fix this behavior.

**Questions:**
1. What changes were made to `haskell/actions/setup` that resolved the connection timeout?
2. Can these changes be applied locally to unblock me from facing the same issue on my local development machine?

Thank you for any insights or guidance on this issue. I’m sure this would be helpful for other users who are encountering similar problems!

**Comment by asarkar** [comment]
This issue is fixed by upgrading to the latest Stack. I nuked ghcup and stack, and installed the latest versions. I assume that's what fixed the action too, the older deprecated action used an older stack that had this bug and the newer action uses a newer stack that doesn't have this bug.

**Comment by andreasabel** [comment]
This might be a Heisenbug.  Network failures of all kinds are beyond our control.
When I encounter such, I either rerun the failed action or ignore the CI failure.

**Comment by asarkar** [comment]
I don’t believe it fits the category of Heisenbug, since it can be consistently reproduced, and reported by multiple people, but I’m glad that it’s fixed by upgrading Stack. Beats options like disabling IPV6 that’s impossible to do anywhere other than one’s home PC. When encountered, it’s a complete show stopper because none of the stack command work.
