### ISSUE TITLE
Proposal: expose cabal GitHub prereleases

### ISSUE THREAD

**Issue by ulysses4ever** [haskell-actions/setup#95]
## Proposal

Cabal automatically publishes [prereleases](https://github.com/haskell/cabal/releases/tag/cabal-head) from the tip of the master branch on every merge to the branch. If the setup action could expose those, this would save some energy for some people when a new GHC is (pre-)released but a new cabal has not been. And more generally, people may want to use unreleased cabal features...

## Alternatives

Currently, there's no indication that ghcup could expose these prereleases on its end: ghcup's metadata approach doesn't seem very suitable for the frequency of the automatic prereleases.

Neither does it seem that the Cabal team has enough resources to cut more formal (less frequent and manual as opposed to automatic) prereleases and submit them to the corresponding ghcup channel.

## Related issues

- https://github.com/haskell/cabal/issues/9917
- https://github.com/haskell/cabal/issues/10467

**Comment by Kleidukos** [comment]
Great idea, this would allow people to integrate the pre-release in their development cycle and have a privileged access to a lot of real-world code bases that would bring the cabal team much needed insight.

**Comment by ulysses4ever** [comment]
Oh my, this has been implemented, actually:

- #45
