### ISSUE TITLE
2 copies of versions.json

### ISSUE THREAD

**Issue by juhp** [haskell-actions/setup#97]
I noticed there are 2 basically identical (modulo indentation) copies of versions.json (in lib/ and src/).
Maybe that is the JS world... a symlink would not be good?

Anyway shouldn't they are least be completely identical files with the same indenting?
Maybe i miss something?

**Comment by andreasabel** [comment]
The `lib/` is auto-generated (from the TS `src/`) but must still be committed so that the JS stuff works.
At least this is how I understood the picture.
The generation of `lib/` is taken care of by the pre-commit hook.
